name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 12
      - run: yarn add
      - run: yarn build
      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build Docker image
        run: docker build --file Dockerfile.deploy -t ${{ secrets.DOCKER_REPO }}:latest -t ${{ secrets.DOCKER_REPO }}:${GITHUB_SHA::8} .
      - name: Publish Docker image
        run: docker push ${{ secrets.DOCKER_REPO }}:${GITHUB_SHA::8}